# Generated by Django 2.2.4 on 2020-04-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='stress_address',
            new_name='street_address',
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('C', 'Complete'), ('W', 'Waiting'), ('R', 'Return')], default='W', max_length=1),
        ),
    ]
