# Generated by Django 2.2.4 on 2020-04-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20200420_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='product',
            new_name='orders',
        ),
    ]
